### ISSUE TITLE
Serialization of uintCV fails

### ISSUE THREAD

**Issue by friedger** [blockstack/connect#151]
When I make a contract call with a clarity value of uint that was created with `uintCV` from  `@stacks/transaction 2.0.0`, I get the following error:
```
TypeError: cv.value.toArrayLike is not a function
    serializeIntCV serialize.ts:44
    serializeCV serialize.ts:135
    args index.ts:131
    _callee3$ index.ts:127
    Babel 8
    _callee6$ index.ts:183
    Babel 8
    openContractCall index.ts:198
    doContractCall use-connect.ts:81
...
```
When using `@stacks/transaction 2.0.0-beta.1`, the serialization is done successfully.

**Comment by friedger** [comment]
maybe related to #150

**Comment by markmhx** [comment]
From @friedger [in Discord](https://discord.com/channels/621759717756370964/745197302255321108/867667894162292746):

> Could we please have an update of connect's dependency @stacks/transactions to 2.0 ? I am struggling with https://github.com/blockstack/connect/issues/151
> I ended up pinning the resolution of transactions lib to 2.0.0-beta.1. This worked.
> 
> I would like to have my app working with transactions 2.0.0 or 3.0.0-beta. However, it does not work because there are some dependencies that work with BigInt and others that don't. In particular connect does not use BigInt while transaction 2.0.0+ does. Any app that requires transaction 2.0.0+ and connect might fail.

**Comment by ahsan-javaid** [comment]
> From @friedger [in Discord](https://discord.com/channels/621759717756370964/745197302255321108/867667894162292746):
> 
> > Could we please have an update of connect's dependency @stacks/transactions to 2.0 ? I am struggling with #151
> > I ended up pinning the resolution of transactions lib to 2.0.0-beta.1. This worked.
> > I would like to have my app working with transactions 2.0.0 or 3.0.0-beta. However, it does not work because there are some dependencies that work with BigInt and others that don't. In particular connect does not use BigInt while transaction 2.0.0+ does. Any app that requires transaction 2.0.0+ and connect might fail.
> 
> @ahsan-javaid could you help with this given your recent work with the transactions package?

@markmhx Created the PR to upgrade the stacks transaction version in connect package. 
PR link: https://github.com/blockstack/connect/pull/152
I don't have permissions to assign the reviewers on this PR. It will be great if you can assign a reviewer on this PR.

**Comment by fbwoolf** [comment]
@friedger can you test this is fixed with the linked PR? https://github.com/blockstack/connect/pull/157

I updated stacks.js packages and need to confirm things are working as expected. I will test on my end with the test-app.

**Comment by Eshwari007** [comment]
@fbwoolf Can you kindly share the test steps for the issue above?
Thanks

**Comment by fbwoolf** [comment]
> @fbwoolf Can you kindly share the test steps for the issue above?
> Thanks

I think this is one that can stay assigned to me through QA. It will be hard to test locally. Basically, we just have to make sure connect modals work as expected and nothing is broken after updating the packages.

**Comment by fbwoolf** [comment]
I did not find any issues when testing with the test-app so moving to QA done. Will wait for feedback from @friedger before merging.
